# Use root/example as user/password credentials
version: '3'

services:
  # app:
  #   build: .
  #   tty: true
  #   ports:
  #     - 3000:3000
  #   volumes: 
  #     - ./:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on: 
  #     adminer:
  #       condition: service_started
  #     db: 
  #       condition: service_healthy
  #   command: sh -c "chmod -R 777 /usr/src/app/node_modules/.prisma/ /usr/src/app/node_modules/prisma/ && npm run db:migrate-dev && npm run db:generate && npm run dev"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ExampleDB
    volumes:
      - ./DB/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: 
      db:
        condition: service_started
